medida = float(input('Uma distância em metros: '))
print(f'A medida de {medida} M corresponde a: ')
print('_' * 20)
print(f'{medida/1000} Km')
print('_' * 20)
print(f'{medida/100} Hm')
print('_' * 20)
print(f'{medida/10} Dam')
print('_' * 20)
print(f'{medida*1} M')
print('_' * 20)
print(f'{medida*10} Dm')
print('_' * 20)
print(f'{medida*100} Cm')
print('_' * 20)
print(f'{medida*1000} Mm')
